import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layouts/Navbar";
import Head from "next/head";

const geistSans = Poppins({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata = {
  title: "ZidView",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        {/* Preconnect to TMDB API */}
        <link
          rel="preconnect"
          href="https://api.themoviedb.org"
          crossOrigin="anonymous"
        />
        <link rel="dns-prefetch" href="https://api.themoviedb.org" />
      </Head>
      <body className={` ${geistSans.variable} antialiased`}>
        <div className=" sticky top-0 z-50 w-full">
          <Navbar />
        </div>
        <main className=" overflow-x-hidden">{children}</main>
      </body>
    </html>
  );
}
